### ISSUE TITLE
main fails typecheck: ToolTimelineEntry fixtures missing required seq in Conversations.render.test.tsx

### ISSUE THREAD

**Issue by M3gA-Mind** [tinyhumansai/openhuman#4948]
## Summary

`main` fails the **Frontend Checks (quality, i18n, docs, coverage)** lane: `tsc` reports two `TS2741` errors in `app/src/pages/__tests__/Conversations.render.test.tsx`, where `ToolTimelineEntry` fixtures are missing the now-required `seq` property. Every PR that syncs `main` inherits the failure.

## Problem

**What happened.** CI Lite on `main` went from `success` at `b48b62327` (08:04) to `failure` at `4a68fd727` (08:18):

```
src/pages/__tests__/Conversations.render.test.tsx(2414,21): error TS2741:
  Property 'seq' is missing in type '{ id: string; name: string; round: number; status: "success"; }'
  but required in type 'ToolTimelineEntry'.
src/pages/__tests__/Conversations.render.test.tsx(2438,21): error TS2741: (same)
##[error]Process completed with exit code 2.
```

**Root cause — a semantic conflict between two individually-green PRs.**

1. #4944 (`b48b62327`, merged 08:04) **added** two `ToolTimelineEntry` fixtures to `Conversations.render.test.tsx` (the cross-thread disclosure-leak test).
2. #4945 (`4a68fd727`, merged 08:18) made **`seq: number` required** on `ToolTimelineEntry` (`app/src/store/chatRuntimeSlice.ts:286`) and updated 12 test files — including this one — but was authored against a base predating #4944, so it never saw those two fixtures.

Each PR passed CI on its own base. Merged 14 minutes apart, the combination breaks `main`. Per-PR CI cannot catch this class of defect; it only appears post-merge.

**Impact.** Release-blocking — `release` is cut from `main`. Every open PR that merges current `main` fails Frontend Checks: already observed on #4912 and #4934 (both Rust-only feature-gate PRs that touch no frontend code, failing purely on inherited breakage). #4913 and #4914 will fail on their next sync.

**Steps to reproduce.**
1. `git checkout main && git pull upstream main`
2. `cd app && pnpm typecheck`
3. Two `TS2741` errors at `Conversations.render.test.tsx:2414` and `:2438`.

Platform: CI (ubuntu runner) and local dev; not platform-specific.

## Solution

Add `seq: 0` to both fixtures in `app/src/pages/__tests__/Conversations.render.test.tsx`:

- **line 2414** — `entries: [{ id: 'a-1', name: 'web_fetch', round: 1, status: 'success' }]`
- **line 2438** — `entries: [{ id: 'b-1', name: 'send_email', round: 1, status: 'success' }]`

`seq: 0` is the correct value and matches #4945's own convention for every comparable fixture it updated (e.g. `timeline/selectors.test.ts`, `SubMascotLayer.test.tsx`, `ToolTimelineBlock.test.tsx`): both are single-entry timelines on distinct threads, so issue-order index `0` is accurate. The change is test-fixture-only — no production code, no behavior change.

## Acceptance criteria

- [ ] **Repro gone** — `pnpm typecheck` passes on `main`; CI Lite green on the merge commit.
- [ ] **Regression safety** — no new coverage needed; the fix restores an existing test file to type-correctness. The two tests (from #4944) continue to assert the same behavior.
- [ ] **Diff coverage ≥ 80%** — n/a in practice (test-fixture-only diff), but the fix PR must not regress the gate.
- [ ] **Unblocks PRs** — #4912 and #4934 pass Frontend Checks after syncing the fixed `main`.

## Related

- #4944 — added the two fixtures (`b48b62327`)
- #4945 — made `seq` required (`4a68fd727`), the merge that surfaced the conflict
- Failing runs: [#4912 Frontend Checks](https://github.com/tinyhumansai/openhuman/actions/runs/29483597333/job/87572799144), [#4934 Frontend Checks](https://github.com/tinyhumansai/openhuman/actions/runs/29483810044/job/87573465870)
- Blocked PRs: #4912, #4934 (observed), #4913, #4914 (on next sync)
