### PR TITLE
fix(voice): ship the voice domain in the desktop build (#4901)

### LINKED ISSUE #4901: Voice transcription unavailable — 'Voice transcription is unavailable in this build' error on latest release
## Summary

Clicking the microphone button to use voice input shows the following error in red:

> "Transcription failed: Voice transcription is unavailable in this build. Restart the OpenHuman desktop app to pick up the latest core sidecar."

The error persists after restarting the app. Voice input is completely non-functional.

## Problem

The error message instructs the user to restart the app to pick up the latest core sidecar, but restarting does not resolve the issue. This suggests the STT (speech-to-text) sidecar binary is either:
- Missing from the build entirely
- Not being bundled correctly for this platform
- Failing to launch silently so the app falls back to this error state

The "Tap and speak" UI is visible and the microphone button is active, but no transcription occurs.

## Steps to reproduce

1. Open OpenHuman desktop app (latest build)
2. Click the microphone button in the chat input area
3. Observe: red error — "Transcription failed: Voice transcription is unavailable in this build"
4. Restart the app as instructed
5. Observe: error persists

## Expected behaviour

- Clicking the microphone button activates voice input
- Speech is transcribed in real time and placed into the chat input
- No error message is shown

## Acceptance criteria

- [ ] Voice transcription works on a clean install of the latest build
- [ ] STT sidecar (`ggml-base-q5_1.bin` or equivalent) is correctly bundled and launched
- [ ] Restarting the app is not required to activate voice — it should work on first launch
- [ ] If the sidecar fails to start, the error message includes a specific reason and a direct action (not just "restart the app")
- [ ] Verified working on macOS, Windows, and Linux

## Related

- Voice feature gate: #4803
- STT model: `ggml-base-q5_1.bin` (default from `effective_stt_model_id`)
- Local AI sidecar management: Rust core / sidecar launcher

### PR DESCRIPTION
**Pull request by CodeGhost21**
## Summary

- The shipped desktop app has been built **without the voice domain** since v0.58.19 — every `openhuman.voice_*` RPC answers `unknown method`, so voice transcription is completely non-functional.
- Root cause: the Tauri shell declares `openhuman_core = { ..., default-features = false }`, which silently dropped the default-ON `voice` feature added by #4833. Fixed by opting `voice` back in explicitly.
- Added a compile-time `const` assert so a voice-less desktop binary **fails the build** instead of shipping and failing silently at runtime.
- Replaced the "restart to pick up the latest core sidecar" error copy — it was written for #1289, refers to a sidecar removed in #1061, and can never resolve a compile-time gate.

## Problem

Since PR #1061 the core runs **in-process inside the Tauri shell**, so the shell's dependency declaration is what actually ships. That declaration has carried `default-features = false` since the in-process move (`app/src-tauri/Cargo.toml:135`, dated 2026-05-16), back when the core crate had **no `[features] default` list at all** — a harmless no-op.

#4833 (implementing #4803) then made `voice` a default-ON compile-time feature so slim/headless builds could drop it. That collided with the pre-existing `default-features = false`: the desktop build stopped enabling `voice`, so the `#[cfg(feature = "voice")]` controller registrations in `src/core/all.rs` (lines 210, 641) were never compiled in, and the whole `openhuman.voice_*` namespace became unknown-method.

Because the gate is **compile-time**, restarting or reinstalling can never help — the code is absent from the binary. This is not a migration or data issue: a clean install of an affected release fails identically.

**Evidence**

- `hound` — reachable *only* via `voice = ["dep:hound", "dep:lettre"]` — was absent from the shell's dependency graph (`cargo tree -i hound` → "did not match any packages") while present in the root crate's graph. Same probe, same worktree; the only difference is `default-features = false`.
- Production Sentry confirms the whole namespace is down, not just STT:
  - [#25260](https://sentry.tinyhumans.ai/organizations/tinyhumans/issues/25260/) `unknown method: openhuman.voice_status` — 46,735 events / 56 users
  - [#25259](https://sentry.tinyhumans.ai/organizations/tinyhumans/issues/25259/) `unknown method: openhuman.voice_server_status` — 46,592 events / 52 users
  - Both first seen `2026-07-14T14:48:59Z`, hours after #4833 landed (`821bac2ee`, 2026-07-14 06:57 +0530). First bad release `0.58.19`, still failing as of `0.61.0`.

Note: the issue hypothesised a missing/mis-bundled `ggml-base-q5_1.bin`. That is a red herring — the model is never reached, and the `voice` gate does not drop whisper-rs (it lives in the inference domain).

## Solution

- **`app/src-tauri/Cargo.toml`** — add `features = ["voice"]`, plus a comment recording that `default-features = false` predates the core's defaults, so every default the core gains must be opted back in here.
- **`app/src-tauri/src/lib.rs`** — `const _: () = assert!(openhuman_core::openhuman::voice::VOICE_COMPILED_IN, ...)`. Cargo features are per-crate, so the shell cannot `#[cfg]` on the core's features; asserting the core's own always-compiled facade is the only way to detect a stubbed build. Placed alongside the existing `compile_error!` desktop-target guard.
- **`src/openhuman/voice/mod.rs`** — expose `VOICE_COMPILED_IN` from the always-compiled facade (`cfg!(feature = "voice")`), so dependents can assert which build they got.
- **`app/src/features/human/voice/sttClient.ts`** — throws a typed `VoiceNotCompiledError` carrying a stable `VOICE_NOT_COMPILED_CODE`, replacing two duplicated inline strings. The English message is kept deliberately (it is what reaches debug logs and Sentry) and retains the `unavailable in this build` substring, which `MicComposer`'s `PERMANENT_ERROR_PATTERNS` matches to suppress a retry/backoff loop that can never succeed against a compile-time gate.
- **i18n** — `MicComposer` previously spliced the raw English error into the *translated* `mic.transcriptionFailed` template ("Transcription failed: {message}"), so the other 13 locales rendered a half-translated sentence. It now branches on the error code and renders `mic.voiceNotCompiled`, added to all 14 locales with real translations. Detection duck-types on `code` rather than `instanceof`, since the error crosses async/retry boundaries where prototypes can be stripped.
- **`src/openhuman/voice/compile_status.rs`** — `VOICE_COMPILED_IN` lives in a sibling module (AGENTS.md requires `mod.rs` be export-only), ungated so it exists in both gate states, with tests pinning it to `cfg!(feature = "voice")` rather than a literal so they hold for both builds.

**Scope note:** the same line also drops `tokenjuice-treesitter` (the core's other default). Not bundled here — the shell separately sets `tinyjuice = { default-features = false }`, suggesting the tree-sitter C build may be avoided deliberately. Filed as #4918, with #4919 to close the whole class in CI.

**Merge note:** the `media` gate (#4804/#4840) landed on `main` mid-review and hit this *same* trap — its author forwarded `media` and documented the rule in a comment, but `voice` stayed broken. The merge conflict was resolved by keeping **both** gates and merging the comments into one rule. Two of the core's three defaults have now been dropped at some point, which is the argument for #4919: a code comment is documentation, not enforcement.

## Submission Checklist

- [x] Tests added or updated (happy path + at least one failure / edge case) per [Testing Strategy](../gitbooks/developing/testing-strategy.md#failure-path-requirement)
- [x] **Diff coverage ≥ 80%** — changed lines meet the gate. The Rust guard is verified red/green (see Impact); frontend paths covered by `sttClient.test.ts` / `MicComposer.test.tsx` (212 related tests pass).
- [x] Coverage matrix updated — `N/A: behaviour-only bug fix, no feature rows added/removed/renamed`
- [x] All affected feature IDs from the matrix are listed in the PR description under `## Related`
- [x] No new external network dependencies introduced (mock backend used per [Testing Strategy](../gitbooks/developing/testing-strategy.md#mock-policy))
- [x] Manual smoke checklist updated if this touches release-cut surfaces — `N/A: no checklist change; voice smoke steps already covered. Verified manually on macOS (see Impact).`
- [x] Linked issue closed via `Closes #NNN` in the `## Related` section

## Impact

**Runtime/platform:** desktop (macOS/Windows/Linux). Restores the entire `openhuman.voice_*` surface — transcription, TTS, availability checks, and the dictation server — all of which were absent from shipped builds.

**Verification**

| Check | Result |
| --- | --- |
| `hound` in shipped shell graph (proxy for `voice`) | absent → **present** |
| Shell build **without** the fix | **fails** `error[E0080]` with the guard message (red) |
| Shell build **with** the fix | compiles, exit 0 (green) |
| Core `cargo check`, voice ON | passes |
| Core `cargo check`, voice OFF (`--no-default-features --features tokenjuice-treesitter`) | passes — facade parity intact, slim builds unaffected |
| Related Vitest suites | 212 pass / 13 files |
| `tsc --noEmit`, ESLint, Prettier, `cargo fmt --check` | clean |
| **Manual: `pnpm dev:app` on macOS, mic → transcript → sent** | **works** |

**Binary size:** re-adds `hound` + `lettre` to the desktop build. These were always intended to ship; their absence was the bug.

**Compatibility / migration:** none. No data, schema, or config involved — purely which code is compiled into the binary. Users on 0.58.19–0.61.x remain broken until they update to a release containing this fix.

## Related

Closes #4901

- Regression introduced by #4833 (implements #4803) — compile-time voice feature gate
- Error copy originally added for #1289 (stale sidecar), obsolete since #1061 (sidecar removed)
- Sentry: OPENHUMAN #25260, #25259
- Follow-up: #4918 — `tokenjuice-treesitter` still un-forwarded (fails soft, no error)
- Follow-up: #4919 — fail CI when the shell drops a default-ON gate (closes this class)
- Feature IDs: `N/A — no coverage-matrix rows affected (behaviour-only fix)`

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved handling when voice transcription isn’t available in the installed app version, replacing confusing “unknown method”/restart guidance with a clear message that voice transcription isn’t included and OpenHuman needs updating.
  - Ensured the mic UI shows the correct localized error state and doesn’t retry when voice support is missing.

- **Localization**
  - Added the “voice transcription not compiled/available” message across all supported languages.

- **Tests**
  - Updated and expanded voice-missing coverage to validate the localized error behavior.
  - Reduced test flakiness by waiting for async UI updates in a canvas validation test.

### CODE REVIEW

**Review by M3gA-Mind — DISMISSED** [review]
# PR #4917 — fix(voice): ship the voice domain in the desktop build (#4901)

## Walkthrough
Since v0.58.19 the shipped desktop app carried `default-features = false` on its `openhuman_core` dependency, which silently dropped the default-ON `voice` compile-time gate added by #4833 — so every `openhuman.voice_*` controller was unregistered and answered "unknown method" at runtime (46k+ Sentry events). This PR re-forwards `voice` (and documents the whole forwarding rule), adds a compile-time `const` assert against the core's always-compiled `VOICE_COMPILED_IN` facade so a voice-less desktop binary now **fails the build** instead of shipping broken, and replaces the stale "restart to pick up the latest core sidecar" copy (obsolete since the sidecar was removed in #1061) with a typed `VoiceNotCompiledError` that drives a properly localized `mic.voiceNotCompiled` message across all 14 locales.

The diagnosis is precise, the fix is minimal and correct, tests are red/green verified, and the AGENTS.md conventions (mod.rs export-only, translations in every locale, no em dashes in translation values) are all respected. **No blocking issues found — approving.**

## Changes

| File | Summary |
| --- | --- |
| `app/src-tauri/Cargo.toml` | Add `voice` to the `openhuman_core` feature list; expand the comment into an enforced "forward every default-ON gate" rule. |
| `app/src-tauri/Cargo.lock` | Re-adds `hound` + `lettre` (reachable only via the `voice` feature) to the shell graph. |
| `app/src-tauri/src/lib.rs` | `const _: () = assert!(openhuman_core::…::VOICE_COMPILED_IN, …)` — turns a silent runtime gap into a build failure. |
| `src/openhuman/voice/compile_status.rs` | New ungated module exposing `VOICE_COMPILED_IN = cfg!(feature = "voice")`, with tests pinning it to the gate in both build states. |
| `src/openhuman/voice/mod.rs` | Re-export `VOICE_COMPILED_IN` from the always-compiled facade. |
| `app/src/features/human/voice/sttClient.ts` | Introduce `VoiceNotCompiledError` + `VOICE_NOT_COMPILED_CODE` + `isVoiceNotCompiledError`; both STT paths throw the typed error on `unknown method`. |
| `app/src/features/human/MicComposer.tsx` | Branch on `isVoiceNotCompiledError` to render localized `mic.voiceNotCompiled` instead of splicing raw English into `{message}`. |
| `app/src/features/human/{sttClient,MicComposer}.test.*` | Updated + new tests for the not-compiled message, restart-copy removal, retry suppression, and localized rendering. |
| `app/src/lib/i18n/*.ts` (14) | Add `mic.voiceNotCompiled` with real translations in every locale. |

## Actionable comments (1)

### 💡 Refactor / suggestion

#### 1. `app/src/features/human/voice/sttClient.ts:45` — make `isVoiceNotCompiledError` a type guard
The predicate returns a bare `boolean`, so callers that later need to read `err.code`/`err.message` after the check still have to cast `err` from `unknown`. Narrowing to `VoiceNotCompiledError` costs nothing (the class already carries `code`) and documents intent. This is polish, not a defect — the current call sites only branch on it.

**Suggested change:**
```ts
// before
export function isVoiceNotCompiledError(err: unknown): boolean {

// after
export function isVoiceNotCompiledError(err: unknown): err is VoiceNotCompiledError {
```

## Nitpicks (1)
- `app/src/lib/i18n/en.ts:405` — a stray blank line now separates `mic.voiceNotCompiled` from the `// Reflections` block. Harmless (matches the section spacing) but slightly asymmetric with the other 13 locales, which inserted the key inline. Leave as-is or drop the blank line.

## Questions for the author (0)
None.

## Verified / looks good
- **Const assert is sound**: `assert!(const_bool, "literal")` is valid in a `const` context, and `VOICE_COMPILED_IN = cfg!(feature = "voice")` evaluating to `false` triggers a genuine E0080 compile failure — matches the PR's red/green table. The message is a bare literal (no format args), which const panic requires.
- **`mod.rs` stays export-only** (AGENTS.md): the constant lives in sibling `compile_status.rs`; `mod.rs` only re-exports it. `compile_status.rs` and its `pub mod` line are correctly ungated so they exist in both feature states, and `stub.rs` does not redefine the symbol, so there's no glob/explicit re-export collision when voice is OFF.
- **Retry suppression is intact**: `VoiceNotCompiledError.message` retains the `unavailable in this build` substring, which `PERMANENT_ERROR_PATTERNS` matches → `isTransientError` returns `false` → the error rethrows through `transcribeWithRetry`/`transcribeWithFallback` without a WAV re-encode, and reaches `finalizeRecording` with its prototype intact.
- **Duck-typing on `code`** (not `instanceof`) is the right call for an error crossing async/retry boundaries, and a pinning test (`keeps the "unavailable in this build" substring`) guards the coupling.
- **i18n complete**: all 14 locale files (`ar bn de en es fr hi id it ko pl pt ru zh-CN`) carry `mic.voiceNotCompiled`; interpolation-free values, no `U+2014` em dashes in any translation value.
- **Test coverage**: the "does not retry permanent errors" and cloud/factory `unknown method` tests were updated to assert the new copy and the *absence* of the restart hint; a new MicComposer test proves the localized string (not raw developer copy) reaches `onError`.

File: app/src/features/human/voice/sttClient.ts [hunk 1]
```diff
@@ -4,6 +4,52 @@ import { callCoreRpc } from '../../../services/coreRpcClient';
...
+    this.name = 'VoiceNotCompiledError';
+  }
+}
+
+/**
+ * Duck-typed on `code` rather than `instanceof`: the error crosses async +
+ * retry boundaries, and structured-clone/serialization paths can strip the
+ * prototype while preserving own properties.
+ */
+export function isVoiceNotCompiledError(err: unknown): boolean {
```
Comment (M3gA-Mind) [inline app/src/features/human/voice/sttClient.ts]: **💡 Suggestion — make `isVoiceNotCompiledError` a type guard**

The predicate returns a bare `boolean`, so a caller that later reads `err.code`/`err.message` after the check still has to cast `err` from `unknown`. Narrowing to `VoiceNotCompiledError` costs nothing (the class already carries `code`) and documents intent. Polish, not a defect — current call sites only branch on it.

```ts
// before
export function isVoiceNotCompiledError(err: unknown): boolean {

// after
export function isVoiceNotCompiledError(err: unknown): err is VoiceNotCompiledError {
```

**Comment by M3gA-Mind** [comment]
## W5 review (comment-only — the maintainer decides merge)

I ran our review harness and then verified the substantive claims against the code myself. Two process notes up front:
- The harness defaulted to posting an **Approved** review; I've **dismissed** that — this is a comment-only pass, the approve/merge call is the human's.
- Its inline type-guard suggestion (below) still stands as a comment.

### CI: the 2 "failures" are stale, not real
`gh pr checks` shows green, but the check-runs API lists 2 `failure`s. Both are the **same non-code check** — **PR Submission Checklist** (the PR-template/description validator) — which ran three times on the head commit `e21285d1`:

| time (UTC) | conclusion |
|---|---|
| 18:57:42 | ❌ failure |
| 19:00:10 | ❌ failure |
| 19:02:18 | ✅ **success** |

The two early failures were superseded by the 19:02 pass (the checklist re-runs on PR-description edits). **Every substantive check is green** — Rust Core Coverage, Rust Tauri Coverage, Frontend Checks (quality/i18n/docs/coverage), Rust Feature-Gate Smoke (gates off), Rust Quality (fmt/clippy), PR CI Gate. No real code failure. (The only open review state is CodeRabbit's earlier `CHANGES_REQUESTED` from 14:59 — worth a re-check against the current head.)

### Fix correctness — sound
- **Root cause & fix confirmed against the diff.** `app/src-tauri/Cargo.toml`: `openhuman_core` went `features = ["media"]` → `["media", "voice"]`. That re-forwards the default-ON `voice` gate that `default-features = false` had been silently dropping, which is exactly why the whole `openhuman.voice_*` namespace answered "unknown method". Minimal, on-target.
- **Compile-time assert is robust.** `const _: () = assert!(openhuman_core::openhuman::voice::VOICE_COMPILED_IN, "...")` in `src-tauri/src/lib.rs`, backed by an **ungated** `pub const VOICE_COMPILED_IN = cfg!(feature = "voice")` in `voice/compile_status.rs` (re-exported at `voice::` in `mod.rs`, so it resolves in both feature states). Because the const is per-crate and the shell/core are separate Cargo worlds, a future dropped forward can't be masked by feature-unification — it fails the build with E0080 rather than shipping broken again. The pinning test asserts the const tracks the gate in both builds. 
- **Frontend half coherent.** Typed `VoiceNotCompiledError` replaces the stale "restart the sidecar" copy with the localized `mic.voiceNotCompiled` (present in all 14 locales; em-dashes appear only in code comments / the internal Error message, not in any locale value, so the i18n em-dash gate passes).

### Non-blocking nits
1. `isVoiceNotCompiledError(err: unknown): boolean` → narrow to a type guard `err is VoiceNotCompiledError` for call-site narrowing (harness posted this inline).
2. The internal English `VoiceNotCompiledError` message uses an em dash (`— the voice module…`). Harmless (it's a code string used for the `unavailable in this build` substring match, not a translation), but the repo otherwise avoids U+2014 in prose.

**Verdict: sound.** The diagnosis, the feature-forward fix, and the compile-time guard are all correct and well-tested; CI is effectively green. Deferring the approve/merge decision to the maintainer.

**Comment by M3gA-Mind** [comment]
## W5 re-review (comment-only — head `9c3a8e14`)

Re-reviewed after the new push. Still comment-only; the merge call is the maintainer's.

### ✅ Nit #1 resolved
`isVoiceNotCompiledError` is now a proper type guard — `err is VoiceNotCompiledError`, with the body duck-typing on `.code === VOICE_NOT_COMPILED_CODE`, which matches the class's `readonly code` field. Correct narrowing; behavior unchanged. Thanks for the quick turnaround.

### ⛔ New blocker — AI-attribution trailer on the new commit
Commit `9c3a8e146` ("refactor(voice): narrow isVoiceNotCompiledError to a type guard") ends with:

```
Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>
```

This repo treats `Co-Authored-By: Claude …` / "Generated with" trailers as a **merge blocker**. Please strip it (`git rebase`/`commit --amend` to drop the trailer, force-push) before this is merged. Not a code issue — purely the commit metadata.

### CI
The two earlier "failures" are gone — `PR Submission Checklist` now passes cleanly at this head. The rest of CI Lite (Frontend Checks, Rust Core/Tauri Coverage, Rust Quality, Feature-Gate Smoke) is still running for `9c3a8e14`; no failures so far, and the delta over the previously-green head is just this one type-annotation line plus a routine `upstream/main` merge, so I don't expect surprises. I'll flag if anything flips red.

### Still open (non-blocking, unchanged)
- The internal `VoiceNotCompiledError` message uses an em dash (`— the voice module…`). Harmless (code string, not a translation), just noting the repo otherwise avoids U+2014 in prose.

**Verdict: still sound on the code.** One non-code merge blocker to clear (drop the AI co-author trailer); CI completing green so far.

**Review by M3gA-Mind — DISMISSED** [review]
Approving the code (head `9c3a8e14`). The diagnosis and fix are correct and well-guarded:
- `openhuman_core` features `["media"]` → `["media","voice"]` re-forwards the default-ON gate that `default-features=false` had been dropping (the root cause of the `openhuman.voice_*` "unknown method" storm).
- The compile-time `const _: () = assert!(openhuman_core::…::VOICE_COMPILED_IN, …)` (ungated per-crate const, separate Cargo world) turns a future regression into a build failure (E0080) instead of a silent ship.
- Frontend: typed `VoiceNotCompiledError` → localized `mic.voiceNotCompiled` across all 14 locales; retry-suppression preserved; `isVoiceNotCompiledError` is now a proper `err is VoiceNotCompiledError` type guard.

Two things still to clear before merge (approval is a code sign-off, not a bypass of these):
1. **CI Lite is still running** at this head — the required PR CI Gate / Frontend / Rust Coverage jobs haven't reported yet (0 failures so far; the delta over the previously all-green head is one type-annotation line + a routine main merge).
2. **Drop the AI-attribution trailer** — commit `9c3a8e146` carries `Co-Authored-By: Claude Opus 4.8 …`, which this repo blocks merges on. Amending/force-pushing to remove it will change the head SHA and dismiss this approval, so please re-request once it's clean.

**Review by M3gA-Mind — APPROVED** [review]
