### ISSUE TITLE
Modifications needed to run on Linux

### ISSUE THREAD

**Issue by airdogvan** [tinyhumansai/openhuman#2861]
As is this appimage does NOT run on Linux.  In order to get it running you need:

1 - run ./OpenHuman_*.AppImage --appimage-extract

2 - Create a script that tells it where to find the libraries and create an openhuman binary:

cat > ./openhuman << 'EOF'
#!/bin/bash
APPDIR="$HOME/appimage/squashfs-root"  # adjust path if needed (the folder where you ran the extract command)
LD_LIBRARY_PATH="$APPDIR/shared/lib:$LD_LIBRARY_PATH" "$APPDIR/bin/OpenHuman" "$@"
EOF
chmod +x ./openhuman

### Triage Assessment
- The AppImage launch issue partially addressed by #2307 (sharun bundling) and #2829 (AppRun CWD fix) but not confirmed resolved.
- Reporter's specific distro unconfirmed. Second reporter on Ubuntu 24.04 aarch64: "cannot execute binary file" — likely an architecture mismatch (OpenHuman ships amd64 AppImages only).
- Remaining: on modern distros (Arch/CachyOS, Fedora 41+) the bundled libssl.so.3 from Ubuntu 24.04 build env may be too old. See #3716 for overlapping report.

### Proposed Scope
- In-scope: verify AppImage works on Ubuntu 24.04 amd64, Fedora 41, Arch Linux (container-based test).
- Not in scope: aarch64 Linux packaging (architecture gap, not a bug).

### Implementation Steps
1. Add a CI smoke step that runs `--help` on the built AppImage under Fedora 41 (container) to catch segfaults before release. Use `scripts/ci/appimage-smoke.sh`.
2. If libssl version skew is confirmed, build AppImage with a newer base image (e.g., Fedora 41 instead of Ubuntu 24.04) or unbundle OpenSSL and let the host libcrypto resolve.
3. Close after both steps shipped AND reporter confirms a fresh AppImage works on their distro.

### Verification
- `appimage-smoke.sh` runs `./OpenHuman*.AppImage --help` and checks exit code 0 in Fedora 41 container.
- Manual verification on Ubuntu 24.04 amd64, Arch, openSUSE Tumbleweed.

**Comment by oxoxDev** [comment]
**Status / parity check — likely fixed, needs reporter confirmation (~80%)**

The manual `LD_LIBRARY_PATH` wrapper this issue describes should no longer be necessary. Merged to `main`:
- #2307 — bundles the sharun AppImage loader.
- #2829 — `cd "$APPDIR"` in AppRun before exec so sharun's preload resolves the bundled libraries with the correct CWD.

Together these make the AppImage resolve its bundled libs at launch without the hand-rolled library-path export.

What's **remaining**: this hasn't been confirmed against the reporter's specific distro, and no one has tied the sharun work back to this issue. Could you grab the latest AppImage and confirm it launches without the manual wrapper? If it still fails, the exact distro + the linker error would help. Keeping open pending that.

**Comment by airdogvan** [comment]
This is the result in **Ubuntu** 24.04 LTS: bash ./OpenHuman_0.57.18_aarch64.AppImage  
                                                                                                                   
./OpenHuman_0.57.18_aarch64.AppImage: ./OpenHuman_0.57.18_aarch64.AppImage: cannot execute binary file


and this on **Tumbleweed** latest version: 

bash ./OpenHuman_0.57.18_aarch64.AppImage                                                                            
./OpenHuman_0.57.18_aarch64.AppImage: ./OpenHuman_0.57.18_aarch64.AppImage: cannot execute binary file


Of course in both cases I did a chmod +x for each.
