### PR TITLE
feat(harness): stop identical-call loops and hand back stuck sub-agents as incomplete

### LINKED ISSUE #4088: [Harness] Add circuit breaker for repeated identical tool calls
## Summary

The harness has no **circuit breaker** for repeated identical tool calls. When an agent issues the same tool with the same arguments N times in a row, nothing intervenes — it can repeat indefinitely until the step budget runs out.

## Simulated example

```
→ http_get(url="https://example.test/status")
← 503
→ http_get(url="https://example.test/status")   # identical args
← 503
→ http_get(url="https://example.test/status")   # x10, unchanged
```

## Expected behavior

After K consecutive identical (tool, args) calls, the harness should break the loop — inject a system notice ("repeated identical call detected; change approach or stop"), force a strategy change, or terminate the turn with an explanatory message.

## Suggested fix / acceptance

- Track a rolling hash of recent `(tool, normalized_args)`.
- Trip after K (default ~3) identical repeats; surface a notice and require a different action.
- Configurable threshold; counts reset on any distinct successful call.

---
_Surfaced by our internal agent-simulation harness during large-scale, aggressive fuzz testing of agent behaviors. The example above is synthetic and contains no real data._

### LINKED ISSUE #4091: [Harness] Escalate to orchestrator (Core) after repeated sub-agent failures
## Summary

A specialist/sub-agent that cannot make progress does not **escalate back to the orchestrator (Core)**. The spawn hierarchy supports handing control back, but in practice stuck sub-agents keep trying locally instead of returning a structured "cannot proceed" to the parent.

## Simulated example

```
[sub-agent: integrations] → call_service() → unavailable
                          → call_service() → unavailable
                          → (loops locally; never returns control to Core)
```

## Expected behavior

After repeated failed attempts, the sub-agent returns a concise structured failure to the orchestrator ("blocked on <capability>, tried <N>, suggest <X>"), letting Core retry differently, route elsewhere, or inform the user.

## Suggested fix / acceptance

- Standard "escalate to parent" return contract for sub-agents.
- Trigger after K failed attempts or a hard blocker (missing capability/permission).
- Orchestrator handles the escalation rather than the run silently ending.

---
_Surfaced by our internal agent-simulation harness during large-scale, aggressive fuzz testing of agent behaviors. The example above is synthetic and contains no real data._

### LINKED ISSUE #4095: [Harness] Agents enter unproductive loops (repeated tool calls, no progress)
## Summary

In large-scale aggressive fuzz testing with our internal agent-simulation harness, agents frequently enter **unproductive loops**: they re-issue the same (or trivially similar) tool calls repeatedly, make no progress toward the goal, and never terminate or change approach. The turn/step budget is consumed with no result.

This is a **tracking issue** for the "no-progress loop" failure class. Specific mechanisms are tracked in the sub-issues below.

## Simulated example

A simulated agent asked to "find the service config and report the active port" loops on the same call:

```
→ list_dir(path="/app")
← [directory listing]
→ list_dir(path="/app")          # identical call, no new information
← [directory listing]
→ list_dir(path="/app")          # repeats ~15×, never opens a file
...
(step budget exhausted — no answer produced)
```

## Impact

- Wasted compute and latency; step/turn budget exhausted with nothing returned.
- Appears "stuck" — no progress, no resolution, no message.

## Sub-issues

Tracked below.

---
_Surfaced by our internal agent-simulation harness during large-scale, aggressive fuzz testing of agent behaviors. The example above is synthetic and contains no real data._

**Sub-issues:** #4088 · #4089 · #4090

### LINKED ISSUE #4096: [Harness] Agents don't escalate / hand back control when stuck
## Summary

In fuzz testing with our internal agent-simulation harness, agents that get stuck rarely **escalate or hand back control**. Instead of surfacing the blocker to the orchestrator/Core or to the user, they keep retrying silently until the budget runs out.

This is a **tracking issue** for the missing-escalation failure class; mechanisms are in the sub-issues.

## Simulated example

```
→ attempt_action()  → blocked
→ attempt_action()  → blocked
→ attempt_action()  → blocked
(agent never says "I'm blocked on X — handing back" and never asks for input)
```

## Impact

- Failures are invisible: no handoff, no question to the user, no fallback path taken.
- The run dead-ends instead of recovering via escalation.

## Sub-issues

Tracked below.

---
_Surfaced by our internal agent-simulation harness during large-scale, aggressive fuzz testing of agent behaviors. The example above is synthetic and contains no real data._

**Sub-issues:** #4091 · #4092

### PR DESCRIPTION
**Pull request by sanil-23**
## Summary

- Add `RepeatCallGuard` (#4088 / #4095): a circuit breaker that halts an agent turn after **3 consecutive identical `(tool, args)` calls**, independent of whether each call succeeds — closing the loop-detection gap the two existing guards miss.
- Add a `TurnStop` discriminator + `SubagentRunStatus::Incomplete` (#4091 / #4096): a stuck or capped sub-agent now hands the orchestrator a structured `[SUBAGENT_INCOMPLETE]` envelope (partial progress + blocker) instead of a success-framed result.
- All delegation tools (`spawn_subagent`, `spawn_async_subagent`, `continue_subagent`, `dispatch`) and status consumers updated; one orchestrator-prompt rule added to relay incomplete results rather than re-run unchanged.

## Problem

Fuzz testing surfaced two agent-reliability failures:

- **Unproductive loops (#4095):** agents re-issue the *same* tool call repeatedly and never terminate. The existing guards don't catch this when the call **succeeds**: `RepeatFailureGuard` resets on every success (`tool_loop.rs`), and `RepeatOutputGuard` hashes the assistant **narration** alongside the call, so trivially varied prose around an identical call resets its streak.
- **No handback when stuck (#4096):** when a sub-agent got stuck (circuit-breaker halt) or hit its iteration cap, the runner returned its summary as `SubagentRunStatus::Completed` and the delegation tool wrapped it in `ToolResult::success(...)`. The partial-progress prose was delivered, but **nothing marked it as incomplete** — so a weak orchestrator could narrate it as done or silently re-spawn the same delegation.

## Solution

**Loop detection (#4095).** New `RepeatCallGuard` in `tool_loop.rs`, wired into `engine/core.rs` before tool execution. It keys only on canonical `(tool, args)` (sorted-key JSON, so reordered keys can't evade it), is independent of success, and trips at `REPEAT_CALL_THRESHOLD = 3`. Any distinct intervening call resets the streak, so read→write→read and varied-arg enumeration never trip it.

**Stuck handback (#4096).** New `TurnStop` enum (`Final` / `Halted` / `Cap` / `EarlyExit`) replaces the `hit_cap` bool on `TurnEngineOutcome`, giving callers an explicit reason a turn ended. The sub-agent runner maps `Halted`/`Cap` to a new `SubagentRunStatus::Incomplete { reason }`, carrying the partial-progress summary as `output`. Delegation tools render a `[SUBAGENT_INCOMPLETE]` envelope (success + partial progress, **not** the "nothing happened" error envelope) and a `GROUNDING_BODY` prompt rule tells the orchestrator to relay it and not re-run unchanged.

Design notes:
- The two fixes share the same stop-detection path; `TurnStop` also back-fills the new repeat-call halt site.
- Adding the `Incomplete` variant is compiler-enforced — every exhaustive `match` on `SubagentRunStatus` was updated.
- Reason/suggestion text is generated from data the harness already has (breaker counters, failure class); no extra LLM calls.

## Submission Checklist

- [x] Tests added or updated (happy path + at least one failure / edge case) — repeat-call guard unit tests (trips / resets-on-distinct / varied-args / reordered-keys), engine `Halted` + `Cap` `TurnStop` tests, and an end-to-end `stuck_subagent_returns_incomplete_status` test.
- [x] **Diff coverage ≥ 80%** — targeted tests cover the new guard, the `TurnStop` mapping, and the end-to-end `Incomplete` path. `cargo-llvm-cov` + `diff-cover` was not run locally (heavy); the per-tool envelope arms are exercised indirectly and CI's `rust-core-coverage`/`coverage-gate` is the authoritative check.
- [x] Coverage matrix updated — N/A: behaviour change to existing harness loop; no feature row added/removed/renamed.
- [x] All affected feature IDs from the matrix are listed under `## Related` — N/A: no matrix rows touched.
- [x] No new external network dependencies introduced — no dependencies added; all tests use scripted in-process providers.
- [x] Manual smoke checklist updated if this touches release-cut surfaces — N/A: core agent-loop logic, no release-cut UI surface.
- [x] Linked issue closed via `Closes #NNN` in the `## Related` section.

## Impact

- Runtime: Rust core only (`src/`). No Tauri shell, frontend, or dependency changes.
- Behaviour: an agent spinning on an identical call now halts after 3 repeats with a no-progress summary; a stuck/capped sub-agent now reports `Incomplete` with its partial progress instead of a success-framed result. Clean finishes and the iteration-cap checkpoint prose are unchanged.
- No migration, security, or compatibility implications.

## Related

- Closes #4088
- Closes #4091
- Closes #4095
- Closes #4096
- Tracking issues #4095 (loop detection) and #4096 (escalation / handback) are closed by this PR. #4090 (monitor self-suspend) and #4092 (escalate-to-user) are intentionally out of scope; #4097 is already covered by the orchestrator's existing checkpoint/empty-final handling.
- Follow-up PR(s)/TODOs: optional per-tool envelope-arm tests for stricter diff coverage; make `REPEAT_CALL_THRESHOLD` configurable (#4088 stretch).

---

### Linear Issue

- Key: N/A
- URL: N/A

### Commit & Branch

- Branch: `feat/harness-loop-and-incomplete-handback`
- Commit SHA: see PR head

### Validation Run

- [x] `pnpm --filter openhuman-app format:check` — N/A, no frontend (app) changes.
- [x] `pnpm typecheck` — N/A, no TypeScript changes.
- [x] Focused tests: `cargo test --lib` for `engine::core` (9), `subagent_runner` (57), `agent::prompts` (44), `agent_orchestration` (226), `agent::harness::session` (136) — all pass.
- [x] Rust fmt/check (if changed): `cargo fmt` applied; `cargo check --manifest-path Cargo.toml` clean (0 errors); full lib test build (`--no-run`) succeeds.
- [x] Tauri fmt/check (if changed): N/A, no `app/src-tauri` changes.

### Validation Blocked

- `command:` `pnpm rust:check` (pre-push hook)
- `error:` fails in a fresh worktree (missing vendored CEF libs), unrelated to this change
- `impact:` pushed with `--no-verify`; no Tauri/CEF code touched, so the hook's check does not apply to this diff.

### Behavior Changes

- Intended behavior change: halt identical-call loops after 3 repeats; mark stuck/capped sub-agent runs as `Incomplete` with partial progress.
- User-visible effect: agents stop wasting the step budget spinning on one call, and a blocked delegation surfaces "did not finish, here's what I got" instead of a fabricated success.

### Parity Contract

- Legacy behavior preserved: clean final responses, the iteration-cap checkpoint prose, `AwaitingUser` pauses, and the channel/CLI `ErrorCheckpoint` path are unchanged. Existing 2-identical-call tests stay green (threshold is 3).
- Guard/fallback/dispatch parity checks: `RepeatCallGuard` sits alongside the existing `RepeatFailureGuard`/`RepeatOutputGuard` without altering them; `TurnStop` replaces the `hit_cap` bool with equivalent `Cap` semantics at its single read site.

### Duplicate / Superseded PR Handling

- Duplicate PR(s): None
- Canonical PR: This PR
- Resolution: N/A

## Summary by CodeRabbit

* **New Features**
  * Agents and sub-agents now surface an explicit **Incomplete** outcome (stop reason + partial output) when they halt before finishing.
  * Added a **repeat identical tool-call** safeguard that stops stuck loops when the same tool call is re-issued without progress.

* **Bug Fixes**
  * Improved turn termination handling with clearer **halt vs cap** behavior, including correct memory autosave suppression.
  * Prevents repeated successful identical calls from continuing indefinitely.

* **Documentation**
  * Updated grounding guidance to avoid fabricating or silently re-running unchanged calls after incomplete/blocked results.  

* **Tests**
  * Added coverage for repeat-call stopping and incomplete sub-agent status behavior.

### CODE REVIEW

File: src/openhuman/agent/harness/engine/core.rs [hunk 1]
```diff
@@ -757,7 +781,52 @@ pub(crate) async fn run_turn_engine(
...
+        // resets on success) both miss.
+        {
+            let mut call_sig = String::new();
+            for call in &tool_calls {
+                call_sig.push('\u{1}');
+                call_sig.push_str(&call.name);
+                call_sig.push('\u{1}');
+                call_sig.push_str(&call.arguments.to_string());
+            }
+            if let Some(reason) = call_guard.record(&call_sig) {
```
[the remark this answers is not in the document]
Comment (sanil-23) [reply src/openhuman/agent/harness/engine/core.rs]: Fixed in 202366eb4. Added `is_repeat_call_exempt` (currently `wait_subagent`) and exempt all-poll batches from both no-progress breakers, and moved the repeat-call breaker post-execution gated on success so identical *failing* calls stay the failure guard's domain. New end-to-end test: 5 identical `wait_subagent` polls past both thresholds finish normally.

**Comment by M3gA-Mind** [comment]
Maintainer review changes (commit d9a551eb9):

- **`src/openhuman/agent/harness/engine/core_tests.rs` (~line 861)** — added the missing `max_output_tokens` argument to the `run_turn_engine(...)` call in the summarizing-checkpoint test. **Why:** `main` added `max_output_tokens: u32` as parameter #15 of `run_turn_engine` (`core.rs:153`); this PR's test still called it with 18 args, so after merging current main the **Rust Core Coverage** lane failed to compile (`error[E0061]: this function takes 19 arguments but 18 arguments were supplied`). The fix passes the same `crate::openhuman::inference::provider::AGENT_TURN_MAX_OUTPUT_TOKENS` constant the two sibling call sites in the same file (`:195`, `:387`) already use. Test-only, mechanical signature alignment — no behavior change.

This was the sole compile error in the coverage log; both CodeRabbit findings (Incomplete-arm checkpoint cleanup; isolating the repeat-CALL guard with varied narration) were already addressed by the author in prior commits.

**Comment by M3gA-Mind** [comment]
@coderabbitai review

**Review by M3gA-Mind — APPROVED** [review]
